# TODO Update to point to the released quickstarts and image
# Will need a diff commit in the upstream-to-product repository
build:
  uri: https://github.com/jboss-developer/jboss-eap-quickstarts.git
  ref: xp-5.0.x
  contextDir: microprofile-reactive-messaging-kafka
  mode: s2i
deploy:
  replicas: 1
  env:
    - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
      value: my-cluster-kafka-bootstrap:9092
